mss-boot-io/mss-boot-admin-antd

- config/admin.json
- config/config.ts
- config/routes.ts
- package.json
- pnpm-lock.yaml
- src/locales/zh-CN/menu.ts
- src/pages/TaskList/Control/$id.tsx
- src/pages/TaskList/index.tsx
- src/services/admin/index.ts
- src/services/admin/role.ts
- src/services/admin/task.ts
- src/services/admin/typings.d.ts
> 💥 feat(模块): task enabled

- config/routes.ts
- src/locales/en-US/menu.ts
- src/locales/zh-CN/menu.ts
- src/pages/Option/index.tsx
- src/services/admin/index.ts
- src/services/admin/option.ts
- src/services/admin/typings.d.ts
> 💥 feat(option): enabled

- README.md
- README.zh-CN.md
> 📝 docs(README): update document

- src/pages/User/Github/callback.tsx
- src/requestErrorConfig.ts
> 🐛 fix(login): github oauth2

- .github/workflows/cf.yml
- .github/workflows/release.yml
- src/pages/Menu/index.tsx
> 🐛 fix(menu): delete param

- .github/workflows/beta.yml
- .github/workflows/cf.yml
- .github/workflows/release.yml
> fix workflow docker

- .github/workflows/beta.yml
> 🐛 fix(workflow): workflow

- src/pages/Task/index.tsx
> 🐛 fix(task): form init set body

- config/config.ts
- src/util/fixMenuItemIcon.tsx
> 💥 feat(menu): support a link

- src/components/RightContent/AvatarDropdown.tsx
- src/locales/en-US/settings.ts
- src/pages/AppConfig/components/base.tsx
- src/pages/AppConfig/components/security.tsx
- src/pages/AppConfig/index.tsx
- src/pages/Menu/index.tsx
> 🐛 fix(menu): parent select empty

- src/pages/AppConfig/components/security.tsx
- src/pages/Field/index.tsx
- src/pages/User/Login/index.tsx
https://github.com/mss-boot-io/mss-boot-admin/issues/48 #48
> 🐛 fix(field): missing binding model

- src/pages/User/Login/index.tsx
> 🐛 fix(login): oauth state invalid

- src/locales/en-US/pages.ts
- src/locales/zh-CN/pages.ts
- src/pages/Tenant/index.tsx
https://github.com/mss-boot-io/mss-boot-admin/issues/103
> 🐛 fix(tenant): expire error

- src/pages/Menu/index.tsx
https://github.com/mss-boot-io/mss-boot-admin/issues/108
> 🐛 fix(menu): binding api error

- .github/workflows/release.yml
- config/config.prod.local.ts
- package.json
> 💥 feat(login): support run in local

- src/pages/Account/Settings/components/AccessToken.tsx
- src/pages/Account/Settings/index.tsx
- src/services/admin/index.ts
- src/services/admin/typings.d.ts
- src/services/admin/userAuthToken.ts
> 💥 feat(login): support person access token

- src/pages/Account/Settings/components/AccessToken.tsx
- src/pages/Menu/index.tsx
- src/pages/User/Login/index.tsx
> 💥 feat(login): fix github state error

- src/pages/User/Login/forget.tsx
- src/pages/User/Login/index.tsx
- src/services/admin/typings.d.ts
> 💥 feat(login): fix: add useBy params

- src/locales/en-US/pages.ts
- src/locales/zh-CN/pages.ts
- src/pages/Post/index.tsx
- src/pages/Task/index.tsx
- src/pages/User/Login/index.tsx
- src/services/admin/typings.d.ts
> 💥 feat(task): add k8s provider

- src/locales/en-US/pages.ts
- src/locales/zh-CN/pages.ts
- src/pages/Task/index.tsx
> 🐛 fix(task): fix command and args type

- config/routes.ts
- src/app.tsx
- src/pages/AppConfig/components/security.tsx
- src/pages/User/Login/index.tsx
- src/pages/User/Login/register.tsx
- src/services/admin/typings.d.ts
> 💥 feat(user): support register

- src/pages/Task/index.tsx
> 🐛 fix(task): args and command show error

- .github/workflows/cf.yml
- wrangler.toml
> :bug: fix: github workflow

- src/locales/en-US/pages.ts
- src/locales/zh-CN/pages.ts
- src/pages/Account/Center/index.less
- src/pages/Account/Center/index.tsx
> 💥 feat(account-center): add account center

- src/locales/en-US/pages.ts
> fix(pages): correct spelling of 'copyright' in website fields
